server:
  port: 1314
  host: "0.0.0.0"
  mode: "debug" # "release" or "debug"

database:
  type: "sqlite"
  path: "data/ech0.db"

upload:
  maxsize: 5242880
  savepath: "data/images/"
  allowedtypes: 
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/jpg"

auth:
  jwt:
    secret: "HelloEch0s!"
    expires: 2592000 # 30天（单位秒）
    issuer: "ech0s"
    audience: "ech0s"